name: Run end to end

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:
  schedule:
    - cron: "23 17 * * *"

# Cancel previous runs of the same PR but do not cancel previous runs on main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TERM: linux
  TERMINFO: /etc/terminfo
  MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }}
  MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}
  MODAL_ENVIRONMENT: examples

jobs:
  run-e2e:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup

      - name: Run end-to-end
        run: |
          modal run le_inference.py
          modal deploy le_inference.py
          modal run le_client.py --dry-run --n 1 --subsample 1
          modal run le_client.py --no-dry-run --n 100 -- subsample 100
          modal run les_evals.py
